name: scrape
on:
  schedule:
    - cron: '0 * * * *'  # Execution each o'clock

  workflow_dispatch:  # Manual

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager beautifulsoup4 python-telegram-bot selenium-stealth

    - name: Run the scraping script
      run: python scraper.py
